### ISSUE TITLE
Read up on Unsupervised Learning - present next week

### ISSUE THREAD

**Issue by MattClarkson** [00bryan123/DeepReg#2]
https://arxiv.org/pdf/1704.06065.pdf

**Comment by MattClarkson** [comment]
Good presentation.

Also read Daniel's classic: http://dx.doi.org/10.1109/42.796284

A couple more questions. If you can paste a quick explanation below, or discuss at the next supervision, then we can close this ticket.

* Explain the difference between a fully supervised deeply learnt registration algorithm, and an unsupervised one.
* How would you make a fully supervised deeply learnt registration algorithm.
* If you trained an unsupervised deeply learnt registration algorithm on MR images of the brain - what would the algorithm do if given as input pairs of cardiac MR?

**Comment by 00bryan123** [comment]
Thanks for the questions Matt. The paper you sent was quite helpful to clarify an expand on the applicaitons of FFD and B-splining in image registration. I've included my responses to the questions, and please let me know how you think of them!

1. The difference between fully supervised DL registration and unsupervised would be the training data. A fully supervised network would be trained with a dataset including the inputs and outputs, whereas unsupervised would be trained with only input data. Moreover, fully supervised network's cost function would calculate the similarity between our prediction with respect to the datset output. 

2. In the context of medical image registration, our fully supervised model would be trained with a dataset containing pairs of images as well as a corresponding registered image. Deeply learnt algorithm means that we will layer neural networks as our training architecture. 

Clarification question: Since our network is trained to output registered images to be as similar as our dataset, would this mean that the registration performance of our alogirthm would be dependent and LIMITED to the registration performance of our dataset? 

3. I think that the algorithm won't register our cardiac MRI pairs because brain and cardiac MRI are vastly different in terms of anatomy. Since the algorithm is trained on brain MRI, the neural networks would've learnt to feature select regions of interest unique to brain anatomy. The learnt feaures of a brain anatomy is dissimilar to heart anatomy so overal I think the algorithm won't register the image pair well.

**Comment by 00bryan123** [comment]
Hello
